# Generated by Django 4.1.13 on 2024-03-09 18:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usermodule', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='feedback',
            table=None,
        ),
    ]
