# Generated by Django 5.0 on 2024-01-08 07:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_ss'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Ss',
        ),
    ]
