# Generated by Django 5.0 on 2024-02-13 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UploadedFiles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attachment_file', models.FileField(upload_to='uploads/')),
                ('csv_file', models.FileField(upload_to='uploads/')),
            ],
            options={
                'db_table': 'UploadedFiles',
            },
        ),
    ]
