# Generated by Django 5.0 on 2024-02-14 14:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mailapp', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UploadedFiles',
        ),
    ]
