# Generated by Django 4.0.3 on 2024-02-01 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employermodule', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobdetails',
            name='salary_offered',
            field=models.CharField(max_length=255, null='false'),
        ),
    ]
