# Generated by Django 4.0.3 on 2024-02-01 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employermodule', '0005_alter_jobdetails_education_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobdetails',
            name='education',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='jobdetails',
            name='salary_offered',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='jobdetails',
            name='work_location',
            field=models.CharField(max_length=255),
        ),
    ]
