# Generated by Django 4.1.13 on 2024-03-09 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Flight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FlightId', models.CharField(max_length=3)),
                ('FlightName', models.CharField(max_length=200)),
                ('FlightSource', models.CharField(max_length=10)),
                ('FlightDestination', models.CharField(max_length=150)),
            ],
            options={
                'db_table': 'Flight',
            },
        ),
    ]
